import React, { useState, useEffect } from 'react';
import {
  CheckSquare,
  Square,
  Plus,
  Trash2,
  AlertCircle,
  Clock,
  User,
  Tag,
  RefreshCw,
  ChevronDown,
  ChevronRight,
  CheckCircle,
  XCircle
} from 'lucide-react';
import { PlanItemWithContent } from '../../types/plan';

/**
 * PreServiceChecklist Component
 *
 * Comprehensive pre-service checklist with:
 * - Auto-generated tasks from plan items
 * - Manual custom tasks
 * - Category grouping (Technical, Worship, Media, etc.)
 * - Priority levels
 * - Assignee tracking
 * - Completion tracking
 * - Progress overview
 */

export interface ChecklistItem {
  id: string;
  title: string;
  description?: string;
  category: ChecklistCategory;
  priority: 'low' | 'normal' | 'high' | 'critical';
  completed: boolean;
  completedAt?: Date;
  completedBy?: string;
  assignee?: string;
  autoGenerated: boolean;
  sourceItemId?: string; // ID of plan item that generated this
  order: number;
}

export type ChecklistCategory =
  | 'technical'
  | 'worship'
  | 'media'
  | 'people'
  | 'facility'
  | 'content'
  | 'other';

interface PreServiceChecklistProps {
  planItems: PlanItemWithContent[];
  checklist: ChecklistItem[];
  onChange: (checklist: ChecklistItem[]) => void;
  readOnly?: boolean;
  className?: string;
}

const CATEGORY_CONFIG: Record<
  ChecklistCategory,
  { label: string; icon: React.ComponentType<any>; color: string }
> = {
  technical: {
    label: 'Technical Setup',
    icon: AlertCircle,
    color: 'text-yellow-400 bg-yellow-900/20'
  },
  worship: {
    label: 'Worship Team',
    icon: User,
    color: 'text-purple-400 bg-purple-900/20'
  },
  media: {
    label: 'Media & Presentations',
    icon: CheckSquare,
    color: 'text-blue-400 bg-blue-900/20'
  },
  people: {
    label: 'People & Teams',
    icon: User,
    color: 'text-green-400 bg-green-900/20'
  },
  facility: {
    label: 'Facility',
    icon: Tag,
    color: 'text-orange-400 bg-orange-900/20'
  },
  content: {
    label: 'Content Ready',
    icon: CheckSquare,
    color: 'text-cyan-400 bg-cyan-900/20'
  },
  other: {
    label: 'Other',
    icon: Tag,
    color: 'text-gray-400 bg-gray-900/20'
  }
};

const PRIORITY_CONFIG = {
  low: { label: 'Low', color: 'text-gray-400' },
  normal: { label: 'Normal', color: 'text-blue-400' },
  high: { label: 'High', color: 'text-yellow-400' },
  critical: { label: 'Critical', color: 'text-red-400' }
};

export const PreServiceChecklist: React.FC<PreServiceChecklistProps> = ({
  planItems,
  checklist,
  onChange,
  readOnly = false,
  className = ''
}) => {
  const [expandedCategories, setExpandedCategories] = useState<Set<ChecklistCategory>>(
    new Set(Object.keys(CATEGORY_CONFIG) as ChecklistCategory[])
  );
  const [showAddForm, setShowAddForm] = useState(false);
  const [editingItemId, setEditingItemId] = useState<string | null>(null);

  // Auto-generate checklist items from plan
  const generateChecklistFromPlan = () => {
    const generatedItems: ChecklistItem[] = [];
    let order = checklist.filter((item) => !item.autoGenerated).length;

    planItems.forEach((planItem) => {
      // Song items
      if (planItem.type === 'song') {
        generatedItems.push({
          id: `check-song-${planItem.id}`,
          title: `Prepare song: ${planItem.title}`,
          description: 'Ensure lyrics are loaded and displayed correctly',
          category: 'worship',
          priority: 'normal',
          completed: false,
          autoGenerated: true,
          sourceItemId: planItem.id,
          order: order++
        });

        if (planItem.assignee) {
          generatedItems.push({
            id: `check-song-team-${planItem.id}`,
            title: `Confirm worship team for: ${planItem.title}`,
            description: `Assigned to: ${planItem.assignee}`,
            category: 'people',
            priority: 'high',
            completed: false,
            autoGenerated: true,
            sourceItemId: planItem.id,
            assignee: planItem.assignee,
            order: order++
          });
        }
      }

      // Scripture items
      if (planItem.type === 'scripture') {
        generatedItems.push({
          id: `check-scripture-${planItem.id}`,
          title: `Verify scripture: ${planItem.title}`,
          description: planItem.scriptureRef
            ? `Check ${planItem.scriptureRef} is loaded correctly`
            : 'Verify scripture reference',
          category: 'content',
          priority: 'high',
          completed: false,
          autoGenerated: true,
          sourceItemId: planItem.id,
          order: order++
        });
      }

      // Presentation items
      if (planItem.type === 'presentation') {
        generatedItems.push({
          id: `check-presentation-${planItem.id}`,
          title: `Test presentation: ${planItem.title}`,
          description: 'Verify all slides display correctly and animations work',
          category: 'media',
          priority: 'high',
          completed: false,
          autoGenerated: true,
          sourceItemId: planItem.id,
          order: order++
        });
      }

      // Items with technical cues
      if (planItem.settings) {
        try {
          const settings = JSON.parse(planItem.settings);
          if (settings.cues && settings.cues.length > 0) {
            generatedItems.push({
              id: `check-cues-${planItem.id}`,
              title: `Setup technical cues for: ${planItem.title}`,
              description: `${settings.cues.length} cue(s) to configure`,
              category: 'technical',
              priority: 'high',
              completed: false,
              autoGenerated: true,
              sourceItemId: planItem.id,
              order: order++
            });
          }
        } catch (e) {
          // Ignore parse errors
        }
      }
    });

    // Add general checklist items
    const generalItems: ChecklistItem[] = [
      {
        id: 'check-general-sound',
        title: 'Sound check completed',
        description: 'Test all microphones and audio levels',
        category: 'technical',
        priority: 'critical',
        completed: false,
        autoGenerated: true,
        order: order++
      },
      {
        id: 'check-general-lights',
        title: 'Lighting setup verified',
        description: 'Confirm all lighting cues and presets',
        category: 'technical',
        priority: 'high',
        completed: false,
        autoGenerated: true,
        order: order++
      },
      {
        id: 'check-general-screens',
        title: 'Display screens working',
        description: 'All projection screens and confidence monitors operational',
        category: 'technical',
        priority: 'critical',
        completed: false,
        autoGenerated: true,
        order: order++
      },
      {
        id: 'check-general-backup',
        title: 'Backup plan ready',
        description: 'Alternative arrangements in case of technical issues',
        category: 'other',
        priority: 'normal',
        completed: false,
        autoGenerated: true,
        order: order++
      }
    ];

    // Merge with existing manual items
    const manualItems = checklist.filter((item) => !item.autoGenerated);
    const newChecklist = [...manualItems, ...generatedItems, ...generalItems];

    onChange(newChecklist);
  };

  const handleToggleComplete = (itemId: string) => {
    onChange(
      checklist.map((item) =>
        item.id === itemId
          ? {
              ...item,
              completed: !item.completed,
              completedAt: !item.completed ? new Date() : undefined
            }
          : item
      )
    );
  };

  const handleAddItem = () => {
    const newItem: ChecklistItem = {
      id: `check-manual-${Date.now()}`,
      title: '',
      category: 'other',
      priority: 'normal',
      completed: false,
      autoGenerated: false,
      order: checklist.length
    };

    onChange([...checklist, newItem]);
    setEditingItemId(newItem.id);
    setShowAddForm(true);
  };

  const handleUpdateItem = (itemId: string, updates: Partial<ChecklistItem>) => {
    onChange(checklist.map((item) => (item.id === itemId ? { ...item, ...updates } : item)));
  };

  const handleDeleteItem = (itemId: string) => {
    onChange(checklist.filter((item) => item.id !== itemId));
  };

  const toggleCategory = (category: ChecklistCategory) => {
    const newExpanded = new Set(expandedCategories);
    if (newExpanded.has(category)) {
      newExpanded.delete(category);
    } else {
      newExpanded.add(category);
    }
    setExpandedCategories(newExpanded);
  };

  // Group items by category
  const itemsByCategory = checklist.reduce((acc, item) => {
    if (!acc[item.category]) {
      acc[item.category] = [];
    }
    acc[item.category].push(item);
    return acc;
  }, {} as Record<ChecklistCategory, ChecklistItem[]>);

  // Calculate progress
  const totalItems = checklist.length;
  const completedItems = checklist.filter((item) => item.completed).length;
  const progressPercent = totalItems > 0 ? Math.round((completedItems / totalItems) * 100) : 0;
  const criticalIncomplete = checklist.filter(
    (item) => item.priority === 'critical' && !item.completed
  ).length;

  const renderChecklistItem = (item: ChecklistItem) => {
    const isEditing = editingItemId === item.id;

    if (isEditing) {
      return (
        <div key={item.id} className="bg-gray-800 rounded-lg border-2 border-blue-500 p-4">
          <ChecklistItemForm
            item={item}
            onSave={(updates) => {
              handleUpdateItem(item.id, updates);
              setEditingItemId(null);
              setShowAddForm(false);
            }}
            onCancel={() => {
              if (!item.title) {
                handleDeleteItem(item.id);
              }
              setEditingItemId(null);
              setShowAddForm(false);
            }}
          />
        </div>
      );
    }

    return (
      <div
        key={item.id}
        className={`
          flex items-start gap-3 p-3 rounded-lg border border-gray-700
          ${item.completed ? 'bg-gray-900/50 opacity-60' : 'bg-gray-800'}
          ${!readOnly ? 'hover:border-gray-600' : ''}
          transition-all
        `}
      >
        {/* Completion Checkbox */}
        {!readOnly && (
          <button
            onClick={() => handleToggleComplete(item.id)}
            className={`
              w-5 h-5 rounded border-2 flex items-center justify-center flex-shrink-0 mt-0.5
              ${
                item.completed
                  ? 'bg-green-500 border-green-500'
                  : 'border-gray-600 hover:border-gray-500'
              }
              transition-colors
            `}
          >
            {item.completed && <CheckCircle className="w-3 h-3 text-white" />}
          </button>
        )}

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span
              className={`font-medium ${item.completed ? 'line-through text-gray-500' : 'text-white'}`}
            >
              {item.title}
            </span>
            <span
              className={`text-xs px-2 py-0.5 rounded-full ${PRIORITY_CONFIG[item.priority].color}`}
            >
              {PRIORITY_CONFIG[item.priority].label}
            </span>
            {item.autoGenerated && (
              <span className="text-xs px-2 py-0.5 rounded-full bg-blue-900/30 text-blue-400">
                Auto
              </span>
            )}
          </div>

          {item.description && (
            <div className="text-sm text-gray-400 mt-1">{item.description}</div>
          )}

          <div className="flex items-center gap-3 mt-2 text-xs text-gray-500">
            {item.assignee && (
              <div className="flex items-center gap-1">
                <User className="w-3 h-3" />
                <span>{item.assignee}</span>
              </div>
            )}
            {item.completed && item.completedAt && (
              <div className="flex items-center gap-1">
                <Clock className="w-3 h-3" />
                <span>
                  Completed {new Date(item.completedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
            )}
          </div>
        </div>

        {/* Actions */}
        {!readOnly && !item.autoGenerated && (
          <div className="flex items-center gap-1">
            <button
              onClick={() => setEditingItemId(item.id)}
              className="p-2 text-gray-400 hover:text-white hover:bg-gray-700 rounded transition-colors"
              title="Edit item"
            >
              <Tag className="w-4 h-4" />
            </button>
            <button
              onClick={() => handleDeleteItem(item.id)}
              className="p-2 text-red-400 hover:text-red-300 hover:bg-gray-700 rounded transition-colors"
              title="Delete item"
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className={`${className}`}>
      {/* Header with Progress */}
      <div className="bg-gray-800 rounded-lg border border-gray-700 p-4 mb-4">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h3 className="text-lg font-medium text-white">Pre-Service Checklist</h3>
            <div className="text-sm text-gray-400 mt-1">
              {completedItems} of {totalItems} completed
              {criticalIncomplete > 0 && (
                <span className="ml-2 text-red-400">
                  ({criticalIncomplete} critical items remaining)
                </span>
              )}
            </div>
          </div>

          {!readOnly && (
            <div className="flex items-center gap-2">
              <button
                onClick={generateChecklistFromPlan}
                className="flex items-center gap-2 px-3 py-2 bg-green-600 text-white rounded hover:bg-green-700 transition-colors text-sm"
              >
                <RefreshCw className="w-4 h-4" />
                Generate from Plan
              </button>
              <button
                onClick={handleAddItem}
                className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors text-sm"
              >
                <Plus className="w-4 h-4" />
                Add Item
              </button>
            </div>
          )}
        </div>

        {/* Progress Bar */}
        <div className="relative h-3 bg-gray-900 rounded-full overflow-hidden">
          <div
            className={`h-full transition-all duration-500 ${
              progressPercent === 100
                ? 'bg-green-500'
                : progressPercent >= 80
                ? 'bg-yellow-500'
                : 'bg-blue-500'
            }`}
            style={{ width: `${progressPercent}%` }}
          />
        </div>
        <div className="text-center text-sm font-medium text-gray-300 mt-1">
          {progressPercent}%
        </div>
      </div>

      {/* Checklist Items by Category */}
      <div className="space-y-3">
        {(Object.keys(CATEGORY_CONFIG) as ChecklistCategory[]).map((category) => {
          const items = itemsByCategory[category] || [];
          if (items.length === 0) return null;

          const config = CATEGORY_CONFIG[category];
          const Icon = config.icon;
          const isExpanded = expandedCategories.has(category);
          const categoryCompleted = items.filter((item) => item.completed).length;
          const categoryTotal = items.length;
          const categoryPercent =
            categoryTotal > 0 ? Math.round((categoryCompleted / categoryTotal) * 100) : 0;

          return (
            <div key={category} className="bg-gray-900 rounded-lg border border-gray-700">
              {/* Category Header */}
              <div
                onClick={() => toggleCategory(category)}
                className="flex items-center justify-between p-3 cursor-pointer hover:bg-gray-800/50 transition-colors"
              >
                <div className="flex items-center gap-3">
                  {isExpanded ? (
                    <ChevronDown className="w-5 h-5 text-gray-400" />
                  ) : (
                    <ChevronRight className="w-5 h-5 text-gray-400" />
                  )}
                  <div className={`p-2 rounded ${config.color}`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="font-medium text-white">{config.label}</div>
                    <div className="text-xs text-gray-400">
                      {categoryCompleted}/{categoryTotal} completed
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  {categoryPercent === 100 ? (
                    <CheckCircle className="w-5 h-5 text-green-500" />
                  ) : categoryPercent > 0 ? (
                    <div className="text-sm text-yellow-400">{categoryPercent}%</div>
                  ) : (
                    <XCircle className="w-5 h-5 text-gray-600" />
                  )}
                </div>
              </div>

              {/* Category Items */}
              {isExpanded && (
                <div className="p-3 pt-0 space-y-2">
                  {items.map((item) => renderChecklistItem(item))}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Empty State */}
      {totalItems === 0 && (
        <div className="p-8 bg-gray-900/30 rounded-lg border border-gray-700 text-center">
          <CheckSquare className="w-12 h-12 mx-auto mb-3 text-gray-600" />
          <div className="text-lg font-medium text-gray-400 mb-2">No checklist items yet</div>
          <div className="text-sm text-gray-500 mb-4">
            Generate checklist items from your plan or add custom items manually
          </div>
          {!readOnly && (
            <div className="flex items-center justify-center gap-2">
              <button
                onClick={generateChecklistFromPlan}
                className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                Generate from Plan
              </button>
              <button
                onClick={handleAddItem}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
              >
                <Plus className="w-4 h-4" />
                Add Manual Item
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// Checklist Item Form
interface ChecklistItemFormProps {
  item: ChecklistItem;
  onSave: (updates: Partial<ChecklistItem>) => void;
  onCancel: () => void;
}

const ChecklistItemForm: React.FC<ChecklistItemFormProps> = ({ item, onSave, onCancel }) => {
  const [formData, setFormData] = useState<Partial<ChecklistItem>>(item);

  const handleSave = () => {
    if (!formData.title?.trim()) {
      onCancel();
      return;
    }
    onSave(formData);
  };

  return (
    <div className="space-y-3">
      {/* Title */}
      <div>
        <label className="block text-sm font-medium text-gray-300 mb-2">Title *</label>
        <input
          type="text"
          value={formData.title || ''}
          onChange={(e) => setFormData({ ...formData, title: e.target.value })}
          placeholder="e.g., Test microphones and audio levels..."
          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white placeholder-gray-400 focus:outline-none focus:border-blue-500"
          autoFocus
        />
      </div>

      {/* Description */}
      <div>
        <label className="block text-sm font-medium text-gray-300 mb-2">Description</label>
        <textarea
          value={formData.description || ''}
          onChange={(e) => setFormData({ ...formData, description: e.target.value })}
          placeholder="Additional details..."
          rows={2}
          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white placeholder-gray-400 focus:outline-none focus:border-blue-500 resize-none"
        />
      </div>

      <div className="grid grid-cols-2 gap-3">
        {/* Category */}
        <div>
          <label className="block text-sm font-medium text-gray-300 mb-2">Category</label>
          <select
            value={formData.category || 'other'}
            onChange={(e) => setFormData({ ...formData, category: e.target.value as ChecklistCategory })}
            className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white focus:outline-none focus:border-blue-500"
          >
            {(Object.keys(CATEGORY_CONFIG) as ChecklistCategory[]).map((cat) => (
              <option key={cat} value={cat}>
                {CATEGORY_CONFIG[cat].label}
              </option>
            ))}
          </select>
        </div>

        {/* Priority */}
        <div>
          <label className="block text-sm font-medium text-gray-300 mb-2">Priority</label>
          <select
            value={formData.priority || 'normal'}
            onChange={(e) => setFormData({ ...formData, priority: e.target.value as any })}
            className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white focus:outline-none focus:border-blue-500"
          >
            <option value="low">Low</option>
            <option value="normal">Normal</option>
            <option value="high">High</option>
            <option value="critical">Critical</option>
          </select>
        </div>
      </div>

      {/* Assignee */}
      <div>
        <label className="block text-sm font-medium text-gray-300 mb-2">Assignee</label>
        <input
          type="text"
          value={formData.assignee || ''}
          onChange={(e) => setFormData({ ...formData, assignee: e.target.value })}
          placeholder="Person responsible..."
          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white placeholder-gray-400 focus:outline-none focus:border-blue-500"
        />
      </div>

      {/* Actions */}
      <div className="flex items-center justify-end gap-2 pt-2">
        <button
          onClick={onCancel}
          className="px-4 py-2 text-gray-300 border border-gray-600 rounded hover:bg-gray-700 transition-colors"
        >
          Cancel
        </button>
        <button
          onClick={handleSave}
          disabled={!formData.title?.trim()}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          Save Item
        </button>
      </div>
    </div>
  );
};

export default PreServiceChecklist;
